version: '3.4'

services:
  bl.test:
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_URLS=https://+:443;http://+:80
        - ASPNETCORE_HTTPS_PORT=1400
        - IDENTITY-AUTHORITY=https://bl.identity
        - ASPNETCORE_Kestrel__Certificates__Default__Password=Infusion@9999
        - ASPNETCORE_Kestrel__Certificates__Default__Path=/etc/ssl/certs/bonnyland.pfx
    ports:
        - 800:80
        - 400:443
    volumes:
        - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
        - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
        - ./01.Services/Test/BL.Test/bonnyland.pfx:/etc/ssl/certs/bonnyland.pfx
        - bl.test.data:/var/lib/bl.test/data
    depends_on:
        - postgres
        - rabbitmq
        - redis
        - seq
        - mongo

  bl.test1:
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_URLS=https://+:443;http://+:80
        - ASPNETCORE_HTTPS_PORT=1400
        - IDENTITY-AUTHORITY=https://bl.identity
        - ASPNETCORE_Kestrel__Certificates__Default__Password=Infusion@9999
        - ASPNETCORE_Kestrel__Certificates__Default__Path=/etc/ssl/certs/bonnyland.pfx
    ports:
        - 801:80
        - 401:443
    volumes:
        - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
        - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
        - ./01.Services/Test1/BL.Test1/bonnyland.pfx:/etc/ssl/certs/bonnyland.pfx
        - bl.test1.data:/var/lib/bl.test1/data
    depends_on:
        - postgres
        - rabbitmq
        - seq
        - mongo

  envoyapigw:
    container_name: envoy
    ports:
      - 9901:9901
      - 6080:6080
      - 6090:6090
      - 10000:10000
    volumes:
      - ./Files/Envoy/envoy.yaml:/etc/envoy/envoy.yaml
      - ./Files/Envoy/bonnyland.crt:/etc/ssl/certs/bonnyland.crt
      - ./Files/Envoy/bonnyland.key:/etc/ssl/certs/bonnyland.key

  postgres:
    container_name: postgres
    ports:
      - 5432:5432
    environment:
        POSTGRES_USER: "postgres"
        POSTGRES_PASSWORD: "Infusion@9999"
    volumes:
      - postgres-data:/var/lib/postgres/data

  pgadmin:
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=ahmad.lashgari@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=Infusion@9999
    ports:
        - 8001:80
        - 4001:443
    volumes:
      - pgadmin-data:/var/lib/pgadmin/data

  redis:
    container_name: redis
    ports:
        - 6379:6379
    volumes:
      - redis-data:/var/lib/redis/data

  rabbitmq:
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq/data

  seq:
    container_name: seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5341:5341
      - 8002:80
      - 4002:443
    volumes:
      - seq-data:/var/lib/seq/data

  mongo:
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Infusion9999
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/var/lib/mongo/data

  elasticsearch:
    container_name: elasticsearch
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - elasticsearch-data:/var/lib/elasticsearch/data

  kibana:
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - 5601:5601
    volumes:
      - kibana-data:/var/lib/kibana/data
    depends_on:
      - elasticsearch

  prometheus:
    container_name: prometheus
    command: "--config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/prometheus"
    ports:
      - 9090:9090
    volumes:
      - ./Files/Prometheus/:/etc/prometheus/
      - ./data/prometheus/:/prometheus/

  node-exporter:
    container_name: node-exporter
    ports:
      - 9100:9100 

  grafana:
    container_name: grafana
    ports:
      - 3000:3000
    volumes:
      - ./data/grafana/:/var/lib/grafana
    depends_on:
      - prometheus